/sixents_node:                  # 节点名称，需与节点创建时一致
  ros__parameters:
    # 六分 SDK 证书及连接参数
    six_ca_max_len: 3000
    six_mount_point: "RTCM32_GRECJ2"
    six_ak: "4734542738"
    six_as: "fb0vwkac16a5gyqziya6d385rwdg1z75qmjdy66gbzey57k19debgnwnt3v0vkf0"
    six_dev_id: "1421225047560"
    six_dev_type: "SDK"
    six_rtcm_port: 4405

    # CAN FD 发送参数
    canfd_interface: "can1"
    canfd_id: 0x611

    # 日志根目录
    sixents_log_root: "/home/nvidia/autoware/log/sixtens"