# 3个数据一组, 分别表示stop-crawl-slow; 
# 传感器顺序: 头,左,右,尾. 
# 注意: 头部/尾部雷达的数据一定要放在最前/最后
int16[] sensors 




# int16 left_slow_area
# int16 left_crawl_area
# int16 left_stop_area
# int16 back_slow_area
# int16 back_crawl_area
# int16 back_stop_area
# int16 head_slow_area
# int16 head_crawl_area
# int16 head_stop_area
# int16 right_slow_area
# int16 right_crawl_area
# int16 right_stop_area