/**:
  ros__parameters:
    # 停车区 (Stop Zone) - 红色区域，最贴近车尾
    # 坐标顺序: [x1, y1, x2, y2, x3, y3, x4, y4] [左下, 左上, 右上, 右下] 的顺时针/逆时针闭合多边形
    stop_zone_coords: [15, 1200,  217, 850,  1703, 850, 1905, 1200]
    # 减速/线束区 (Caution Zone) - 橙色区域，缓冲区
    caution_zone_coords: [217, 850, 419, 500, 1501, 500, 1703, 850]
    # 预警区 (Warning Zone) - 黄色区域，最远端
    warning_zone_coords: [419, 500, 664, 75, 1256, 75, 1501, 500]