/**:
  ros__parameters:
    tolerance: 2.0
    voxel_leaf_size: 0.2
    min_points_number_per_voxel: 3
    min_cluster_size: 8
    max_cluster_size: 50000
    use_height: true
    input_frame: "base_link"
    # low height crop box filter param
    use_crop_filter: true
    max_x: 150.0
    min_x: -50.0
    max_y: 2.5
    min_y: -2.5
    max_z: 3.5
    min_z: 0.0
    negative: false
