/**:
  ros__parameters:
    inputs: [11, 12, 13, 14, 21]  # See autoware_command_mode_types/sources.hpp
    inputs_names:
      11: stop
      12: main
      13: local
      14: remote
      21: emergency_stop
    rate: 10.0
    builtin_emergency_acceleration: -2.4
    stop_hold_acceleration: -1.5
    emergency_acceleration: -2.4
    moderate_stop_acceleration: -1.5
    diag_timeout_warn_duration: 1.0
    diag_timeout_error_duration: 2.0
    stop_check_duration: 1.0
    enable_command_limit_filter: true
    nominal_filter:
      vel_lim: 2.0
      reference_speed_points: [0.1, 0.3, 2.0, 3.0]
      steer_cmd_lim: [0.65, 0.65, 0.65, 0.65]
      steer_rate_lim_for_steer_cmd: [0.5, 0.5, 0.5, 0.5]
      lon_acc_lim_for_lon_vel: [2.4, 2.4, 2.4, 2.4]
      lon_jerk_lim_for_lon_acc: [3.0, 3.0, 3.0, 3.0]
      lat_acc_lim_for_steer_cmd: [0.8, 0.8, 0.8, 0.8]
      lat_jerk_lim_for_steer_cmd: [2.0, 2.0, 2.0, 2.0]
      lat_jerk_lim_for_steer_rate: 2.0
      steer_cmd_diff_lim_from_current_steer: [0.65, 0.65, 0.65, 0.65]
    transition_filter:
      vel_lim: 2.0
      reference_speed_points: [2.0, 3.0]
      steer_cmd_lim: [0.65, 0.65]
      steer_rate_lim_for_steer_cmd: [0.5, 0.5]
      lon_acc_lim_for_lon_vel: [2.4, 2.4]
      lon_jerk_lim_for_lon_acc: [3.0, 3.0]
      lat_acc_lim_for_steer_cmd: [0.8, 0.8]
      lat_jerk_lim_for_steer_cmd: [2.0, 2.0]
      lat_jerk_lim_for_steer_rate: 2.0
      steer_cmd_diff_lim_from_current_steer: [0.65, 0.65]
