/**:
  ros__parameters:
    update_rate: 10.0
    system_emergency_heartbeat_timeout: 0.5
    use_emergency_handling: false
    check_external_emergency_heartbeat: $(var check_external_emergency_heartbeat)
    enable_cmd_limit_filter: true
    filter_activated_count_threshold: 5
    filter_activated_velocity_threshold: 1.0
    external_emergency_stop_heartbeat_timeout: 0.0
    stop_hold_acceleration: -1.5
    emergency_acceleration: -2.4
    moderate_stop_service_acceleration: -1.5
    stop_check_duration: 1.0
    nominal:
      vel_lim: 2.0
      reference_speed_points: [0.1, 0.3, 2.0, 3.0]
      steer_cmd_lim: [0.65, 0.65, 0.65, 0.65]
      steer_rate_lim_for_steer_cmd: [0.5, 0.5, 0.5, 0.5]
      lon_acc_lim_for_lon_vel: [2.4, 2.4, 2.4, 2.4]
      lon_jerk_lim_for_lon_acc: [3.0, 3.0, 3.0, 3.0]
      lat_acc_lim_for_steer_cmd: [0.8, 0.8, 0.8, 0.8]
      lat_jerk_lim_for_steer_cmd: [2.0, 2.0, 2.0, 2.0]
      lat_jerk_lim_for_steer_rate: 2.0
      steer_cmd_diff_lim_from_current_steer: [0.65, 0.65, 0.65, 0.65]
    on_transition:
      vel_lim: 2.0
      reference_speed_points: [2.0, 3.0]
      steer_cmd_lim: [0.65, 0.65]
      steer_rate_lim_for_steer_cmd: [0.5, 0.5]
      lon_acc_lim_for_lon_vel: [2.4, 2.4]
      lon_jerk_lim_for_lon_acc: [3.0, 3.0]
      lat_acc_lim_for_steer_cmd: [0.8, 0.8]
      lat_jerk_lim_for_steer_cmd: [2.0, 2.0]
      lat_jerk_lim_for_steer_rate: 2.0
      steer_cmd_diff_lim_from_current_steer: [0.65, 0.65]
