/**:
  ros__parameters:
    debug_mode: false
    rosbag_length: 10.0
    maximum_queue_size: 10
    timeout_sec: 0.4
    is_motion_compensated: false
    publish_synchronized_pointcloud: true
    keep_input_frame_in_synchronized_pointcloud: true
    publish_previous_but_late_pointcloud: true
    synchronized_pointcloud_postfix: pointcloud
    input_twist_topic_type: twist
    input_topics: [
                    "/sensing/lidar/top/outlier_filtered/pointcloud",
                    "/sensing/lidar/left/outlier_filtered/pointcloud",
                    "/sensing/lidar/right/outlier_filtered/pointcloud"
                ]
    output_frame: base_link
    matching_strategy:
      type: naive
