/**:
  ros__parameters:
    simple_lane_change_avoidance:
      th_moving_speed: 0.5
      min_forward_distance: 1.0
      max_forward_distance: 50.0
      lateral_margin: 0.3
      min_prepare_distance: 3.0
      min_shifting_distance: 5.0
      shifting_lateral_jerk: 0.2
      min_shifting_speed: 1.0
      return_distance_after_object: 5.0
      publish_debug_marker: true
