# config/can_params.yaml
can_node:
  ros__parameters:
    # CAN 接口配置
    interface: "can0"
    bitrate: 250000
    can0_use: true

    interface1: "can1"
    bitrate1: 250000
    can1_use: false

    txqueuelen: 1000 #发送队列大小
    voice_frame_period_ms: 200   # 0x401最小发送周期
    engage_frame_period_ms: 500  # 0x301最小发送周期

    # 心跳统一配置
    #heartbeat_base_id: 1    # 实际 ID: can0 → 700, can1 → 701
    #heartbeat_period: 25     # 两个接口共用周期（单位：毫秒）