/**:
  ros__parameters:
   x_min: -2.5    #截取点云，x方向最小值
   x_max: 2.0    #截取点云，x方向最大值
   y_min: -4.0   #截取点云，y方向最小值
   y_max: -1.0    #截取点云，y方向最大值
   z_min: -2.2   #截取点云，z方向最小值
   z_max: 1.0    #截取点云，z方向最大值
   sync_diff: 0.1 #点云和图像同步允许时间差（s)
   T_lidar_camera:   #lidar to camera 外参矩阵,
    [ -0.980004,  -0.198389, -0.0152913 , -0.579979,
    -0.0573247,   0.355091,  -0.933072, -0.0293776,
    0.190541,  -0.913538 , -0.359363 , -0.456639,
    0.0, 0.0, 0.0, 1.0]
